### ISSUE TITLE
Bug: error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'LexicalNode | null | undefined'.

### ISSUE THREAD

**Issue by PunkFleet** [facebook/lexical#4313]
Lexical version: v0.9.1

## Steps To Reproduce

1. I don't know what's wrong, but this all works fine in version `0.9.0`, and it also opens fine in local debugging `npm run dev`
2.

```

> admin@0.0.0 build
> tsc && vite build

src/components/editor/plugins/ListMaxIndentLevelPlugin.tsx:33:25 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'LexicalNode | null | undefined'.

33         if ($isListNode(elementNode)) {
                           ~~~~~~~~~~~

src/components/editor/plugins/ListMaxIndentLevelPlugin.tsx:35:36 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'LexicalNode | null | undefined'.

35         } else if ($isListItemNode(elementNode)) {
                                      ~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/components/editor/plugins/ListMaxIndentLevelPlugin.tsx:33

```
Link to code example:
https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/ListMaxIndentLevelPlugin/index.ts

## The current behavior
I got error when i `npm run build`

**Comment by etrepum** [comment]
Can't reproduce
