### ISSUE TITLE
Bug: (typescript) LexicalNode types are missing the `append` method

### ISSUE THREAD

**Issue by atomrc** [facebook/lexical#5502]
Lexical version: 0.12.6

## Steps To Reproduce

1. wire this piece of code in a TypeScript context

```ts
    lexicalEditor.update(() => {
      const root = $getRoot().getLastChild()!;
      const textNode = $createTextNode(text);
      root.append(textNode);
    });
```

Link to code example:

## The current behavior

The following TypeScript error occurs

```
Property 'append' does not exist on type 'LexicalNode'.
```

## The expected behavior

No TypeScript error should be thrown (works with version 0.12.5)

**Comment by cdzombak** [comment]
I'm seeing this as well with 0.12.6.

**Comment by Grantoed** [comment]
Same with getFirstChild()

**Comment by grigoriy-reshetniak** [comment]
Not reproducible in 0.16.0

**Comment by 2wheeh** [comment]
This was probably due to `moduleResolution: bundler` in tsconfig and fixed since v0.14.3

**Comment by petejodo** [comment]
can confirm `getFirstChild()` is missing on `LexicalNode` in `v0.16.1`. `append` is however
