### ISSUE TITLE
Bug: lexical.$getRoot is not a function

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#3860]
Lexical version: 0.7.8

## Steps To Reproduce

TBD (Sorry, it will take me some time to set this up, but others on Discord have encountered the same bug so perhaps they can fill this in).

## The current behavior

Various functions such as `$getNearestBlockElementAncestorOrThrow` and `$insertGeneratedNodes` call into `$findMatchingParent` and end up throwing with `lexical.$getRoot is not a function`.

I've bisected this down to https://github.com/facebook/lexical/commit/f6a278eac8c8ac1c3f1523df5591b57e89c6cda8 from #3238.

Specifically, the additional `import` there:

```ts
import {$splitNode} from '@lexical/utils';
```

If I comment that line out in `Lexical.dev.js` the problem goes away.

It appears to be some sort of cyclic dependency issue. I wonder if lexical core is supposed to be importing from `lexical/utils` like that?

## The expected behavior

It does not throw.

**Comment by birtles** [comment]
Stack 1:

![image](https://user-images.githubusercontent.com/1232595/217746401-f4c7f6fd-d897-4fdd-86e3-9a4e795448d3.png)

Stack 2:

![image](https://user-images.githubusercontent.com/1232595/217746809-97cec946-06e3-4646-aeac-50e1ecfcf689.png)

**Comment by luudv** [comment]
I get same problem

**Comment by nerdess** [comment]
I just upgraded to 

`"@contentful/app-sdk": "^4.23.0",`

and now get a similar error message:

```
lexical.$getRoot is not a function
TypeError: lexical.$getRoot is not a function
    at $findMatchingParent 
```

The `$findMatchingParent` is used in this plugin I use: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx

Any hints would be appreciated!
